# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  workingDirectory: '$(System.DefaultWorkingDirectory)/src'

trigger:
  branches:
    include:
    - main

jobs:
  - job: azure login
    steps:
    - task: CmdLine@2
      inputs:
        script: 'az login -u $(username) -p $(very_secret_pass)'
        displayName: Login in the process


  - job: terraform commands
    steps:

    # Install Terraform
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    
    # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      inputs:
        command: 'init'
        workingDirectory: '$(workingDirectory)/terraform'
        commandOptions: '-backend-config=config.azurerm.tfbackend'
        backendType: 'azurerm'

    # Plan
    - task: TerraformCLI@0
      displayName: Plan Terrafrom Deployment
      inputs:
        command: 'plan'
        workingDirectory: '$(workingDirectory)/terraform'
        commandOption: '-var "sql_admin_password=$(sql_admin_password)" -o tfplan'

    # Apply
    - task: TerraformCLI@0
      displayName: Apply Terraform Deployment Plan
      inputs:
        command: 'apply tfplan'
        workingDirectory: '$(workingDirectory)/terraform'