# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  workingDirectory: '$(System.DefaultWorkingDirectory)/_Terraform-and-Dotnet-CI/.net-app/terraform'

trigger:
  branches:
    include:
    - main

jobs:
#  - job: AzureLogin
#    steps:
#    - task: CmdLine@2
#      inputs:
#        script: 'az login'


  - job: TerraformCommands
    steps:

    # Install Terraform
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
      
    # Init
    - task: TerraformCLI@0
      inputs:
        command: 'init'
#        workingDirectory: '$(workingDirectory)'
        backendType: 'azurerm'
        backendServiceArm: 'Azure DevOps'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(ResourceGroupName)'
        backendAzureRmResourceGroupLocation: '$(ResourceGroupLocation)'
        backendAzureRmStorageAccountName: '$(StorageAccountName)'
        backendAzureRmContainerName: '$(ContainerName)'
        backendAzureRmKey: '$(Key)'
        allowTelemetryCollection: true

    # Validate
    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        workingDirectory: '$(workingDirectory)'
        allowTelemetryCollection: true

    # Plan
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(workingDirectory)'
        environmentServiceName: 'Azure DevOps'
        commandOptions: '-var "sql_admin_password=$(secret_password)"'
        allowTelemetryCollection: true

    # Apply
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: '$(workingDirectory)'
        environmentServiceName: 'Azure DevOps'
        commandOptions: '-var "sql_admin_password=$(secret_password)"'
        allowTelemetryCollection: true