version: 0.2

env:
  variables:
    PROJECT: AspNetChessApp
    DOTNET_FRAMEWORK: 6.0.3

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  
  pre_build:
    commands:
      - cd src
      - dotnet restore

  build:
    commands:
      - dotnet build --no-restore -c Release
      - dotnet test -c Release
  
  post_build:
    commands:
      - dotnet publish --no-build -c Release -o $CODEBUILD_SRC_DIR

artifacts:
  files:
    - ./**/*
