version: 0.2


batch:
  fast-fail: false
  build-list:
    - identifier: terraform_buil
      env:
        secrets-manager:
          AWS_ACCESS_KEY_ID: "IAM_creds:AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "IAM_creds:AWS_SECRET_ACCESS_KEY"
      buildspec: terraform.yml
      ignore-failure: false

    # - identifier: dotnet_build
    #   buildspec: dotnet.yml
    #   ignore-failure: false