version: 0.2


batch:
  fast-fail: false
  build-list:
    - identifier: terraform_build
      buildspec: terraform.yml
      ignore-failure: false

    - identifier: dotnet_build
      buildspec: dotnet.yml
      ignore-failure: false