version: 0.2

env:
  variables:
    PROJECT: AspNetChessApp
    DOTNET_FRAMEWORK: 6.0.3

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  
  pre_build:
    commands:
      - cd src
      - dotnet restore

  build:
    commands:
      - dotnet build --no-restore
      - dotnet test 
  
  post_build:
    commands:
      - dotnet publish -c Release -o ./build_output Web/Chess.Web/Chess.Web.csproj
      - ls ./build_output

artifacts:
#  base-directory: $CODEBUILD_SRC_DIR/myapp
  files:
    - Web/Chess.Web/**/*
