version: 0.2

env:
  variables:
    PROJECT: AspNetChessApp
    DOTNET_FRAMEWORK: 6.0.3

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  
  pre_build:
    commands:
      - cd src
      - dotnet restore

  build:
    commands:
      - dotnet build -c Release -o ${{ env.CODEBUILD_SRC_DIR }}/myapp
      - dotnet test -c Release -o ${{ env.CODEBUILD_SRC_DIR }}/myapp
  
  post_build:
    commands:
      - dotnet publish -c Release -o ${{ env.CODEBUILD_SRC_DIR }}/myapp

artifacts:
  files:
    - ./${{ env.CODEBUILD_SRC_DIR }}/myapp/**/*
