apiVersion: v1
kind: Service
metadata:
    name: chess
spec:
    selector:
        app: chess
    ports:
        - port: 5000
          targetPort: 5000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: chess
spec:
    replicas: 1
    selector:
        matchLabels:
            app: chess
    template:
        metadata:
            labels:
                app: chess
        spec:
            containers:
                - name: app
                  image: stringls/chess-app:v3
                  ports:
                      - containerPort: 5000
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                  imagePullPolicy: Always
