#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#    name: mssql-pvc
#spec:
#    accessModes:
#        - ReadWriteOnce
#    storageClassName: mylocalstorage
#    resources:
#        requests:
#            storage: 256Mi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#    name: local-storage
#spec:
#    storageClassName: mylocalstorage
#    capacity:
#        storage: 256Mi
#    accessModes:
#        - ReadWriteOnce
#    hostPath:
#        path: /home/stringls/data/mssql
#        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
    name: mssql
spec:
    selector:
        app: mssql
    ports:
        - port: 1433
          targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql
spec:
    selector:
        matchLabels:
            app: mssql
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
                - name: mssql
                  image: stringls/mssql-db:latest
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 1433
                  
                  env:
                        - name: MSSQL_PID
                          value: "Developer"
                        - name: ACCEPT_EULA
                          value: "Y"
                        - name: MSSQL_SA_PASSWORD
                          value: "p@ssw0rd"
#                  volumeMounts:
#                    - name: mssqldb
#                      mountPath: /var/opt/mssql
#            volumes:
#                - name: mssqldb
#                  persistentVolumeClaim:
#                    claimName: mssql-pvc
