node {
    def app
    
    stage('Clone Repository') {
        /* Checkout our repository */
        checkout scm
    }
    
    stage('Build docker image') {
        dir('src') {
            /* Build the docker image */
            app = docker.build("stringls/chess-app")
        }
    }
    
/*    stage('Test Image') {
        app.inside {
            sh 'echo "Tests Passed"'
        }
    }
*/    
    stage('Push Image') {
        /* Push images: First is tagged with the build BUILD_NUMBER
        the second is just tagged latest !*/
        docker.withRegistry('https://registry.hub.docker.com', '914765c4-69f5-4046-8596-e8691c5c7fce') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
    
    stage('Deploy to K8s') {
        /* Apply all manifest files */
        dir('~') {
            /* sh "kubectl apply -f ./minikube/" */
            sh "kubectl apply -f ./minikube/service.yaml"
            sh "kubectl apply -f ./miniube/app.yaml"
        }
    }
}
