node {
    def app
    
    environment {
        SERVICE_NAME = "chess-app"
    }
    
    stage('Clone Repository') {
        /* Checkout our repository */
        checkout scm
    }

/*    stage('Build docker image') {
        dir('src') {
            /* Build the docker image 
            app = docker.build("${DOCKERHUB_USERNAME}/${env.SERVICE_NAME}")
        }
    }

/*    stage('Test Image') {
        app.inside {
            sh 'echo "Tests Passed"'
        }
    }
*
    stage('Push Image') {
        /* Push images: First is tagged with the build BUILD_NUMBER
        the second is just tagged latest !*
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
*/
    stage('Deploy to K8s') {
        /* Apply all manifest files */
        withCredentials([string(credentialsId: 'jenkins-token', variable: 'TOKEN')]) {
            sh 'kubectl apply -f ./minikube --token=$<TOKEN>'
            
            /* sh "kubectl apply -f ./minikube/service.yaml"
            sh "kubectl apply -f ./miniube/app.yaml" */
        }
    }
}
