# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: AWS Pipeline

on: [push, workflow_dispatch]

env:
  WEBAPP_NAME: chess-app-dkmk
  REGION: us-west-1
  EB_ENVIRONMENT_NAME: Chessapp-env
#  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '6.0.300'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore
      working-directory: src

    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: src

    - name: Publish
      run: dotnet publish --no-build -c Release -o ${{ env.DOTNET_ROOT }}/myapp
      working-directory: src

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{ env.DOTNET_ROOT }}/myapp
    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
    
    - name: Deploy to EB
      id: deploy-to-webapp
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.WEBAPP_NAME }}
        environment_name: ${{ env.EB_ENVRIONMENT_NAME }}
        version_label: 123
        region: ${{ env.REGION }}
        deployment_package: .
