# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: AWS Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  S3_STATE_BUCKET_NAME: tfstate-s3-bucket
  S3_STATE_BUCKET_KEY: tfstate
  TF_DIR: terraform_aws
  AWS_REGION: eu-central-1
  EB_ENVIRONMENT_NAME: Chessapp-env
  NETCORE_VERSION: '6.0.300'

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'Terraform'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="bucket=${{ env.S3_STATE_BUCKET_NAME }}" -backend-config="key=${{ env.S3_STATE_BUCKET_KEY }}" -backend-config="region=${{ env.AWS_REGION }}"
      working-directory: ${{ env.TF_DIR }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ env.TF_DIR }}

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false
      working-directory: ${{ env.TF_DIR }}
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref = 'refs/heads/main' && github.event_name = 'push'
      run: terraform apply -auto-prove -input=false
      working-directory: ${{ env.TF_DIR }}

  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore
      working-directory: src

    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: src

    - name: Publish
      run: dotnet publish --no-restore --no-build -c Release -o ${{ env.DOTNET_ROOT }}/myapp
      working-directory: src

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{ env.DOTNET_ROOT }}/myapp


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
    
    - name: Deploy to EB
      id: deploy-to-webapp
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.WEBAPP_NAME }}
        environment_name: ${{ env.EB_ENVRIONMENT_NAME }}
        version_label: 123
        region: ${{ env.REGION }}
        deployment_package: .
